name: XrayInformer
version: 2.1.2
description: This plugin protects your server from xrayer
author: sourcemaker
website: http://www.widecraft.de
main: me.sourcemaker.XrayInformer.XrayInformer
commands:
  xcheck:
    description: Xray check for a given player, enter /xcheck reload to reload the config
permissions: 
  xcheck.check:
    description: Allows the xray inform about player
    default: false